server:
  port: 8080
  servlet:
    context-path: /api  # API????

spring:
  # ?????
  datasource:
    url: jdbc:mysql://localhost:3306/warning_system?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root  # ????MySQL???
    password: cwj809153  # ????MySQL??
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA??
  jpa:
    hibernate:
      ddl-auto: update  # ???????
    show-sql: true  # ?????SQL??
    properties:
      hibernate:
        format_sql: true  # ???SQL??

  # JSON??
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

# ?????
app:
  jwt:
    secret: LnQW04INIjqemUT1iYXuAisSBz1owdXwRkzn7uaH4YCoJX6zI2ItDG7IWwOi64aKcdYMKIZETFKwJh+Pi0CtpA== #JWT??
    expiration: 86400000  # token???24??(??)